---
- name: ELK setup
  hosts: localhost

  tasks:
  - name: Disabling SElinux
    command: setenforce 0

  - name: Importing Elastic key
    command: rpm --import https://packages.elastic.co/GPG-KEY-elasticsearch

  - name: Configuring Repository
    yum_repository:
      name: elasticsearch-6.x
      description: Elasticsearch repository for 6.x packages
      baseurl: https://artifacts.elastic.co/packages/6.x/yum
      gpgcheck: yes
      gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      enabled: yes

  - name: Install Elastic
    yum:
      name: "{{item}}"
      state: present
    with_items:
      - elasticsearch
      - java-1.8.0-openjdk
      - logstash
      - kibana
      - epel-release
      - nginx
      - wget

  - name: Updating elastic search config file with localhost entries
    lineinfile:
      path: /etc/elasticsearch/elasticsearch.yml
      regexp: 'network.host:'
      line: 'network.host: localhost'

  - name: Updating elastic search config file with localhost entries
    lineinfile:
      path: /etc/kibana/kibana.yml
      regexp: '#server.host:'
      line: 'server.host: "localhost"'

  - name: Removing default nginx configuration file
    file: path=/etc/nginx/nginx.conf state=absent

  - name: Creating nginx configuration for ELK stack
    get_url: url=https://raw.githubusercontent.com/yogeshraheja/yogan/master/nginx.conf dest=/etc/nginx/

  - name: Changing ngnix.conf
    get_url: url=https://raw.githubusercontent.com/yogeshraheja/yogan/master/kibana.conf dest=/etc/nginx/conf.d/

  - name: Starting Elastic services
    service: name=elasticsearch state=started enabled=yes
    notify: elastic restart

  - name: Starting kibana services
    service: name=kibana state=started enabled=yes
    notify: kibana restart

#  - name: create an admin user, called "kibanaadmin" for kibana GUI
#    htpasswd: path=/etc/nginx/htpasswd.users name=kibanaadmin password=$apr1$7TlcVNs/$LL05V6zPXp8qn1eLrlsnQ.

  - name: Starting Nginx services
    service: name=nginx state=started enabled=yes
    notify: nginx restart

  handlers:

  - name: elastic restart
    service: name=elasticsearch state=restarted

  - name: kibana restart
    service: name=kibana state=restarted

  - name: nginx restart
    service: name=nginx state=restarted
